name: Logdatenauswertung
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipywidgets>=8.1
  - voila>=0.5
  - pandas>=1.5
  - numpy
  - plotly>=5.16
  - notebook
  - jupyterlab
  - jupyterlab_widgets
  - pip
  - pip:
      - voila-gridstack
      - voila-material
