name: Logdatenauswertung
channels:
  - conda-forge
dependencies:
  - python=3.11
  - voila>=0.5
  - ipywidgets>=8.1
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - plotly
  - pip
  - pip:
      - voila-material
      - voila-gridstack
